### ISSUE TITLE
Warning message: UNSAFE_componentWillReceiveProps 

### ISSUE THREAD

**Issue by ernestobalanzar** [mklef121/react-tailwind-table#1]
This component works fine but in the console I'm getting this warning: 

**index.js:1 Warning: Using UNSAFE_componentWillReceiveProps in strict mode is not recommended and may indicate bugs in your code. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state

Please update the following components: Table**

I'm using a stateless functional component, what do you recommend?

**Comment by mklef121** [comment]
Hello @ernestobalanzar this has been noted. Currently the legacy `UNSAFE_componentWillReceiveProps` is used to make re-rendering of the table rows is more efficient.
I will be figuring out a better way to do this. Kindly note in the next minor patch this would be fixed.

**Comment by pnheinsohn** [comment]
¿Still no fix on this?
