### ISSUE TITLE
Any way to add custom TailwindCSS styles?

### ISSUE THREAD

**Issue by perryraskin** [mklef121/react-tailwind-table#2]
After looking through the documentation, I notice there is no info on how to add custom TailwindCSS classes for a custom style. I see the "Look and Feel" section, so does this mean there's only 1 way the table can look?

**Comment by mklef121** [comment]
Thanks @perryraskin for your observation. I will be making a release in a few days that fixes
- This
- Better search optimization
- Remove UNSAFE react lifecycle methods
- Add better pagination
- Improve overall performace

**Comment by pnheinsohn** [comment]
Hi! any news about this upcoming release?

**Comment by mklef121** [comment]
> Hi! any news about this upcoming release?

Bear with me @pnheinsohn actually I've been working on it [most changes are on dev branch](https://github.com/mklef121/react-tailwind-table/tree/dev), I'd wrap up this weekend.

Regards.
