### ISSUE TITLE
type error on import

### ISSUE THREAD

**Issue by jeepers3327** [mklef121/react-tailwind-table#4]
I tried adding this library to my tailwindcss app with typescript but it detects an error upon importing the library.
![image](https://user-images.githubusercontent.com/70475641/119289844-f73f8080-bc7d-11eb-9809-ebbd7ef5ce78.png)

**Comment by mklef121** [comment]
Thanks @jeepers3327 , I've been able to track this issue.

A fix will be applied today.
Thanks

**Comment by mklef121** [comment]
Hello @jeepers3327 kindly uninstall the `react-tailwind-table` package and reinstall again.

You can also let me in on your experience using the table package.

Thanks
