### ISSUE TITLE
it's breaking my pages

### ISSUE THREAD

**Issue by bckd00r** [mklef121/react-tailwind-table#6]
when i switch from my products page to another page everything breaks down

Images:
before
![image](https://user-images.githubusercontent.com/48347237/122939608-722eb080-d37c-11eb-9b78-aa5a50747b61.png)
after
![image](https://user-images.githubusercontent.com/48347237/122939761-94c0c980-d37c-11eb-8bd3-6478dde5aa9c.png)
![image](https://user-images.githubusercontent.com/48347237/122939832-a1452200-d37c-11eb-8684-b10e2d6d8819.png)

**Comment by mklef121** [comment]
Hello @bckd00r, does the project use tailwind or was it installed on a non tailwind application ?

Can you share a link to test this out ?

**Comment by bckd00r** [comment]
> Hello @bckd00r, does the project use tailwind or was it installed on a non tailwind application ?
> 
> Can you share a link to test this out ?

Yes im using with tailwind

**Comment by mklef121** [comment]
Did you use this
```js
import 'react-tailwind-table/dist/index.css';
```
?

**Comment by bckd00r** [comment]
> Did you use this
> 
> ```js
> import 'react-tailwind-table/dist/index.css';
> ```
> 
> ?

yes

**Comment by mklef121** [comment]
@bckd00r  since you  already have tailwind installed on your project, you really would not be needing that line.

You can remove it.

**Comment by bckd00r** [comment]
> @bckd00r  since you  already have tailwind installed on your project, you really would not be needing that line.
> 
> You can remove it.

ok i'll try

**Comment by bckd00r** [comment]
> @bckd00r since you already have tailwind installed on your project, you really would not be needing that line.
> 
> You can remove it.

not working
